#! /bin/bash
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5000 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5001 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5002 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5003 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5004 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5005 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5006 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5007 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5008 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5009 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5010 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5011 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5012 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5013 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5014 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5015 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5016 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5017 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5018 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5019 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5020 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5021 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5022 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5023 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5024 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5025 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5026 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5027 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5028 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5029 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5030 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5031 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5032 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5033 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5034 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5035 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5036 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5037 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5038 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5039 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5040 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5041 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5042 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5043 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5044 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5045 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5046 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5047 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5048 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5049 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5050 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5051 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5052 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5053 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5054 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5055 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5056 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5057 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5058 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5059 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5060 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5061 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5062 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5063 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5064 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5065 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5066 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5067 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5068 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5069 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5070 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5071 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5072 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5073 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5074 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5075 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5076 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5077 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5078 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5079 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5080 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5081 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5082 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5083 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5084 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5085 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5086 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5087 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5088 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5089 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5090 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5091 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5092 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5093 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5094 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5095 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5096 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5097 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5098 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
lxterminal -e ssh bram@127.0.0.1 './Documenten/Illuminator/configuration/runshfile/runRequester.sh 127.0.0.1 5099 /home/bram/Documenten/Illuminator/src/illuminator/models/'&
