scenario:
  name: "Pandalyzer test" # in mosaik so called world
  start_time: '2012-07-06 00:00:00' # ISO 8601 start time of the simulation
  end_time: '2012-07-06 23:45:00' # duration in seconds 
  time_resolution: 900 # time step in seconds (optional). Defaults to 15 minutes (900 s)

models:
- name: Controller1
  type: PandaController
  parameters:
    stations: {} # Figure out dict contents
    power_capacities: {}
    energy_capacities: {}
    initial_SoCs: {}
    ps_connections: {}
    ss_connections: {}
  inputs:
    ncp_powers: {} # Also need to send dictionaries then
  # no outputs
  states:
    cp_powers: {}
    tl_powers: {}

- name: CSVwind1
  type: CSV
  parameters:
  states:

- name: CSVfossil1 # Also causes a problem for pipelining (fossil must read for next time step while outputting for current)
  type: CSV
  parameters:
  states:

- name: CSVload1
  type: CSV
  parameters:
  states:

- name: Wind1
  type: Wind
  parameters:
  inputs:
  outputs:
  states:

- name: Fossil1
  type: Fossil
  parameters:
  inputs:
  # no outputs
  states:

- name: Load1
  type: Load
  parameters:
  inputs:
  outputs:
  # no states

- name: Battery1
  type: Battery
  parameters:
  inputs:
  outputs:
  states:

- name: Station1
  type: Station
  parameters:
    line_reactances: {}
    line_capacities: {}
  inputs:
    ncp_power: 0 # can connect multiple NCP outputs; values will be added together
    cp_power: 0 # from controller
    tl_powers: {} # from controller
    received_tl_powers: {} # from other station
  outputs:
    cp_power: 0
    sent_tl_powers: {}
  states:
    ncp_power: 0 # to controller

- name: Station2
  type: Station
  parameters:
    line_reactances: {}
    line_capacities: {}
  inputs:
    ncp_power: 0 # can connect multiple NCP outputs; values will be added together
    cp_power: 0 # from controller
    tl_powers: {} # from controller
    received_tl_powers: {} # from other station
  outputs:
    cp_power: 0
    sent_tl_powers: {}
  states:
    ncp_power: 0 # to controller

- name: Station3
  type: Station
  parameters:
    line_reactances: {}
    line_capacities: {}
  inputs:
    ncp_power: 0 # can connect multiple NCP outputs; values will be added together
    cp_power: 0 # from controller
    tl_powers: {} # from controller
    received_tl_powers: {} # from other station
  outputs:
    cp_power: 0
    sent_tl_powers: {}
  states:
    ncp_power: 0 # to controller

- name: Station4
  type: Station
  parameters:
    line_reactances: {}
    line_capacities: {}
  inputs:
    ncp_power: 0 # can connect multiple NCP outputs; values will be added together
    cp_power: 0 # from controller
    tl_powers: {} # from controller
    received_tl_powers: {} # from other station
  outputs:
    cp_power: 0
    sent_tl_powers: {}
  states:
    ncp_power: 0 # to controller

- name: Station5
  type: Station
  parameters:
    line_reactances: {}
    line_capacities: {}
  inputs:
    ncp_power: 0 # can connect multiple NCP outputs; values will be added together
    cp_power: 0 # from controller
    tl_powers: {} # from controller
    received_tl_powers: {} # from other station
  outputs:
    cp_power: 0
    sent_tl_powers: {}
  states:
    ncp_power: 0 # to controller

connections:
# Determined by coding
  # CSV connections
- from: CSVwind1.u
  to: Wind1.u

- from: CSVfossil1.bio_frac
  to: Fossil1.bio_frac

- from: CSVload1.load
  to: Load1.load

  # NCP connections
- from: Wind1.wind_gen
  to: Station1.ncp_power

- from: Load1.load_dem
  to: Station3.ncp_power

  # CP connections
- from: Station2.cp_power
  to: Fossil1.req_pow

- from: Station4.cp_power
  to: Battery1.flow2b

  # Controller connections
    # NCP
- from: Station1.ncp_power
  to: Controller1.ncp_powers

- from: Controller1.tl_powers
  to: Station1.tl_powers # !!!Need to encode which powers belong to which station in the transmitted data (maybe use ID as Bram suggested)!!!
  time_shifted: True # !!!
  
- from: Station3.ncp_power
  to: Controller1.ncp_powers

- from: Controller1.tl_powers
  to: Station3.tl_powers
  time_shifted: True # !!!

    # CP
- from: Controller1.cp_powers
  to: Station2.cp_power

- from: Controller1.tl_powers
  to: Station2.tl_powers

- from: Controller1.cp_powers
  to: Station4.cp_power

- from: Controller1.tl_powers
  to: Station4.tl_powers

    # Other
- from: Controller1.tl_powers
  to: Station5.tl_powers

# Determined by cluster configuration
# Inter-station connections
- from: Station1.sent_tl_powers
  to: Station2.received_tl_powers

- from: Station1.sent_tl_powers
  to: Station3.received_tl_powers

- from: Station1.sent_tl_powers
  to: Station5.received_tl_powers

- from: Station2.sent_tl_powers
  to: Station4.received_tl_powers

- from: Station3.sent_tl_powers
  to: Station4.received_tl_powers

- from: Station3.sent_tl_powers
  to: Station5.received_tl_powers

- from: Station4.sent_tl_powers
  to: Station5.received_tl_powers

monitor:
# Somehow need to time-shift peripheral monitor outputs to synchronize (Nuclear is the problem!!!).





# Voor Alje en Bram
connections:
- from: Station1.Sender
  to: Station2.Receiver
  line_id: 1234 # <- dit is het belangrijke gedeelte !!!!!!!!!!!

# Sender en Receiver gaan waarschijnlijk andere namen krijgen
# Specifiek: 
# Sender -> sent_tl_powers; 
# Receiver -> received_tl_powers
